config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  # mount using default path: /email_processor
  mount_griddler
  devise_for :vendors, controllers: {registrations: 'vendors/registrations'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'welcome#home'
  get 'error-message' => 'welcome#error_message'
  resources :automated_responses do
    collection do
      post :turn_off
    end
  end
  resources :response_presets
  resources :vendors_dashboard, only: [:index, :show] do
    collection do
      post :customer_issues
      post :create_messages
      get :form_editor
      get :contact_us
      post :update_dispute
    end
  end
  resources :disputes, only: [:index]

  # get 'welcome/home' => "welcome#home", as: :home
  get 'home/get_tracking_status' => "home#get_tracking_status", as: :get_tracking_status
  get 'home/add_to_store' => "home#add_to_store", as: :add_to_store
  get 'home/update_to_store' => "home#update_to_store", as: :update_to_store
  post 'home/app_uninstalled' => "home#app_uninstalled", as: :app_uninstalled

end

app/views/layouts/shared/_chat_view.html.erb
<% if params[:created_at].present? %>
    <div class="card">
      <div class="card-body">
        <div class="col-lg-12 col-md-12 col-sm-8 col-xs-12 ">
          <div class=" col-lg-6 col-md-6 col-sm-6">
            <ul>
              <li>Order Number:  <%= @dispute.order_number if @dispute.present? %></li>
              <li>Customer Name:  <%= params[:name] if params[:name].present? %></li>
              <li>Customer Email:  <%= params[:email] if params[:email].present? %></li>
              <li>Order Place date:  <%= params[:created_at].to_date if params[:created_at].present? %></li>
              <li>Fulfilment Status:  <%= params[:fulfilled_at] if params[:fulfilled_at].present? %></li>
              <li>Tracking code:  <%= params[:tracking_number] if params[:tracking_number].present? %></li>
              <li>Tracking Url :  <%= params[:tracking_link] if params[:tracking_link].present? %></li>
            </ul>
            <a href="<%= @refund_btn %>" title="Refund" class="btn btn-primary" target="_blank">
              Refund
            </a>
            <br>
            <%= form_for(:update_order_no, :url => update_dispute_vendors_dashboard_index_path, method: :post, remote: true) do |f| %>
              <div class="actions">
                <h6>Update correct order number</h6>
                <%=f.text_field :order_number, placeholder: "Order Number", :value => @dispute_id.order_number %>
                <%= f.hidden_field :dispute_id, value: @dispute_id.id %>
                <%= f.submit "Update", class: 'btn btn-primary'  %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% elsif @disputes_index.present? %>
  <% else %>
  <div class="card">
    <div class="card-body">
      <div class="col-lg-12 col-md-12 col-sm-8 col-xs-12 ">
        <div class=" col-lg-6 col-md-6 col-sm-6">
          <h5>Invalid Order details provided by customer</h5>
          <%= form_for(:update_order_no, :url => update_dispute_vendors_dashboard_index_path, method: :post, remote: true) do |f| %>
            <div class="actions">
              <h6>Update correct order number</h6>
              <%=f.text_field :order_number, placeholder: "Order Number", :value => @dispute_id.order_number %>
              <%= f.hidden_field :dispute_id, value: @dispute_id.id %>
              <%= f.submit "Update", class: 'btn btn-primary'  %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="card">
  <div class="card-body">
    <h4 class="card-title box-title"><label class="check-box make-request">
                            <%= @dispute.first_name if @dispute.present?  %>
                            <%= @dispute.last_name if @dispute.present? %>
                            <%= @dispute.order_number if @dispute.present? %>
                          </label></h4>
    <div class="card-content">
      <% if @dispute.present? %>
          <div class="messenger-box">
            <ul style=" height: 435px; overflow: auto;">
              <li style="width: 100%; float: left;">
                <div class="msg-received msg-container">
                  <div class="avatar">
                    <div class="send-time"><%= time_ago_in_words(@dispute.created_at.to_time) %></div>
                  </div>
                  <div class="msg-box">
                    <div class="inner-box">
                      <div class="name">
                        <%= @dispute.first_name %>
                      </div>
                      <div class="meg">
                        <%= @dispute.description %>
                      </div>
                    </div>
                  </div>
                </div><!-- /.msg-received -->
              </li>
              <% @messages.each do |message| %>
                  <% if message.email == current_vendor.email %>
                      <li style="width: 100%; float: right;">
                        <div class="msg-sent msg-container">
                          <div class="avatar">
                            <div class="send-time"> <%= time_ago_in_words(message.created_at.to_time) %></div>
                          </div>
                          <div class="msg-box">
                            <div class="inner-box">
                              <div class="name">
                                <%= current_vendor.name if current_vendor.name.present? %>
                              </div>
                              <div class="meg">
                                <%= message.body %>
                              </div>
                            </div>
                          </div>
                        </div><!-- /.msg-sent -->
                      </li>
                  <% else %>
                      <li style="width: 100%; float: left;">
                        <div class="msg-received msg-container">
                          <div class="avatar">
                            <div class="send-time"><%= time_ago_in_words(message.created_at.to_time) %></div>
                          </div>
                          <div class="msg-box">
                            <div class="inner-box">
                              <div class="name">
                                <%= @dispute.first_name %>
                              </div>
                              <div class="meg">
                                <%= message.body %>
                              </div>
                            </div>
                          </div>
                        </div><!-- /.msg-received -->
                      </li>
                  <% end %>
              <% end %>
            </ul>
            <%= form_for @chat, :url => create_messages_vendors_dashboard_index_path(@chat), :method => :post, remote: true do |f| %>
                <div class="send-mgs">
                  <div class="yourmsg">
                    <%= f.text_area :body, id: 'TextArea', class: 'form-control', placeholder: "Your Text Goes Here.." %>
                  </div>
                  <%= f.hidden_field :vendor_dispute_id, :value => @dispute.id if @dispute.present? %>
                  <%= f.hidden_field :email, :value => current_vendor.email %>

                  <% if @dispute.present? %>
                      <%= button_tag(class: "btn fa msg-send-btn") do %>
                          <i class="pe-7s-paper-plane"></i>
                      <% end %>
                  <% end %>
                </div>
            <% end %>
            <div class="p-10">
              <% @presets.each do |preset| %>
                  <a href="#" class="btn btn-default btn-custom-class" data-desc="<%= preset.message %>" id="<%= preset.id %>"><%= preset.name %></a>
              <% end %>
              <% if @tracking_no.present? %>
                  <a class=" btn btn-primary" id="enter_track_no">Send Tracking no</a>
                  <div class="hidden" id="tracking_id_content1" style="display: none;"> Here is your tracking number <%= @tracking_no if @tracking_no.present? %> and tracking url <%= @tracking_url if @tracking_url.present? %> </div>
              <% elsif @status.present? %>
                  <a class=" btn btn-primary disabled" id="enter_track_no" disabled="disabled">Send Tracking no</a>
                  <div class="hidden" id="tracking_id_content1"><%= @status %> </div>
              <% else %>
                  <button heref="#" title="No tracking available" class="btn btn-default disabled" disabled="disabled">
                    <span>Send Tracking no</span>
                  </button>
              <% end %>

            </div>
          </div><!-- /.messenger-box -->
      <% else %>
          <div class="messenger-box">
            <ul style=" height: 435px; overflow: auto;">
              No Message available
            </ul>
          </div>

      <% end %>
    </div>
  </div><!-- /.card-body -->
</div><!-- /.card -->





<script>
  $("#enter_track_no").click(function () {
    $("#TextArea").val($("#tracking_id_content1").text());
  });
  $(document).ready(function () {
    $(document).on("click", ".btn-custom-class", function (e) {
      e.preventDefault();
      var value = jQuery(this).data("desc");
      jQuery("#TextArea").text(value);
    });
  });

  // $(document).on("click", ".make-request", function (e) {
  //   e.preventDefault();
  //   var link = $(this).data("href");
  //   $.ajax({
  //     url: link,
  //     type: "GET"
  //   });
  // });
</script>

app/views/layouts/shared/_dispute_list.html.erb
<div class="col-lg-4">
  <div class="card">
    <div class="card-body">
      <% if current_page?(disputes_path) %>
        <h4 class="card-title box-title">Disputes List</h4>
      <% else %>
        <h4 class="card-title box-title">Today's Disputes</h4>
      <% end %>
      <div class="card-content">
        <div class="todo-list" style=" height: 600px; overflow: auto;">
          <div class="tdl-holder">
            <div class="tdl-content">
              <ul>
                <% if @issues.present? %>
                    <% @issues.each do |issue| %>
                        <li>
                          <label class="check-box make-request" data-href="<%= vendors_dashboard_path(issue) %>">
                            <%= issue.first_name %>
                            <%= issue.last_name %>
                            <%= issue.order_number %>
                            <% if issue.vendor_dispute_messages.present? && issue.vendor_dispute_messages.last.read == false %>
                              <i class="fa fa-circle" style="
                              color: #49a342;
                              "></i>
                            <% end %>
                            <br>
                            <% if issue.vendor_dispute_messages.present? && issue.vendor_dispute_messages.last.read == false %>
                              <span><%= "#{issue.vendor_dispute_messages.where(read: false).count} unread messages" %></span>
                              <br>
                            <% end %>
                            <% if issue.vendor_dispute_messages.present? %>
                              <%= "#{time_ago_in_words(issue.vendor_dispute_messages.last.created_at)} ago" %>
                            <% else %>
                              <%= "#{time_ago_in_words(issue.created_at)} ago" %>
                            <% end %>
                          </label>
                        </li>
                    <% end %>
                <% else %>
                    There is no disputes for today
                <% end %>
              </ul>
            </div>
          </div>
        </div> <!-- /.todo-list -->
      </div>
    </div> <!-- /.card-body -->
  </div><!-- /.card -->
</div>

<script>
  $('.make-request').click(function(){
    $(this).children("span").hide();
    $(this).children("i").hide();
  });
</script>