config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  # mount using default path: /email_processor
  mount_griddler
  devise_for :vendors, controllers: {registrations: 'vendors/registrations'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'welcome#home'
  get 'error-message' => 'welcome#error_message'
  resources :automated_responses do
    collection do
      post :turn_off
    end
  end
  resources :response_presets
  resources :vendors_dashboard, only: [:index, :show] do
    collection do
      post :customer_issues
      post :create_messages
      get :form_editor
      get :contact_us
      post :update_dispute
    end
  end
  resources :disputes, only: [:index]

  # get 'welcome/home' => "welcome#home", as: :home
  get 'home/get_tracking_status' => "home#get_tracking_status", as: :get_tracking_status
  get 'home/add_to_store' => "home#add_to_store", as: :add_to_store
  get 'home/update_to_store' => "home#update_to_store", as: :update_to_store
  post 'home/app_uninstalled' => "home#app_uninstalled", as: :app_uninstalled

end

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
    <script type="text/javascript">
      var eventName = typeof(Turbolinks) !== 'undefined' ? 'turbolinks:load' : 'DOMContentLoaded';

      if (!document.documentElement.hasAttribute("data-turbolinks-preview")) {
        document.addEventListener(eventName, function flash() {
          <% if flash[:notice] %>
          ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
          <% end %>

          <% if flash[:error] %>
          ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
          <% end %>

          document.removeEventListener(eventName, flash)
        });
      }
    </script>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer text-center"> 2017 &copy; Elite Admin brought to you by themedesigner.in</footer>

app/views/layouts/_header.html.erb
<header id="header" class="header">
  <div class="top-left">
    <div class="navbar-header">
      <%= image_tag 'swirblogo.png', class: 'navbar-brand' %>
      <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
    </div>
  </div>
  <div class="top-right">
    <div class="header-menu">
      <div class="header-left">
        <button class="search-trigger"><i class="fa fa-search"></i></button>
        <div class="form-inline">
          <%= form_tag disputes_path, :method => 'get', class: "search-form" do %>
              <p>
                <%= text_field_tag :search, params[:search], placeholder: 'Search Dispute', class: "form-control mr-sm-2", id: "search_dispute_input" %>
                <%= submit_tag "Search", name: nil, id: "submit_search" %>
              </p>
          <% end %>
        </div>

        <div class="dropdown for-notification">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-bell"></i>
            <span class="count bg-danger"><%= notifications.count %></span>
          </button>
          <div class="dropdown-menu" aria-labelledby="notification">
            <p class="red">You have <%= notifications.count %> Notification</p>
            <% notifications.each do |notification| %>
                <%= link_to vendors_dashboard_path(notification),class:'dropdown-item media' do %>
                  <i class="fa fa-check"></i>
                  <p><%= notification.order_number %> have a message</p>
                <% end %>
            <% end %>
          </div>
        </div>
        <div class="dropdown for-message">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="message" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-envelope"></i>
            <span class="count bg-primary"><%= messages_count %></span>
          </button>
          <div class="dropdown-menu" aria-labelledby="message">
            <p class="red">You have <%= messages_count %> Mails</p>

          </div>
        </div>
      </div>

      <div class="user-area dropdown float-right">
        <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag 'default-profile-pic.png', class: 'user-avatar rounded-circle' %>
        </a>
        <div class="user-menu dropdown-menu">
          <%= link_to edit_vendor_registration_path, class: "nav-link" do %>
              <i class="fa fa- user"></i>My Profile
          <% end %>
          <%= link_to(' Logout', destroy_vendor_session_path, method: :get, class: " fa fa-power-off") %>
        </div>
      </div>

    </div>
  </div>
</header>
<style>
  #submit_search {
    display: none;
  }
</style>

<script>
  $('#search_dispute_input').on("keypress", function (e) {
    if (e.keyCode == 13) {
      $("#submit_search").click();
    }
  });
</script>

app/views/layouts/_left_side_navbar.html.erb
<!-- Left Panel -->
<aside id="left-panel" class="left-panel">
  <nav class="navbar navbar-expand-sm navbar-default">
    <div id="main-menu" class="main-menu collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to vendors_dashboard_index_path do %>
              <i class="menu-icon fa fa-caret-square-o-up"></i> Dashboard
          <% end %>
        </li>

        <li><%= link_to disputes_path do %>
              <i class="menu-icon fa fa-comment-o"></i> Dispute
          <% end %>
        </li>
        <li><%= link_to new_automated_response_path do %>
              <i class="menu-icon fa fa-pencil-square-o"></i> Automated Response
          <% end %></li>
        <li><%= link_to new_response_preset_path do %>
              <i class="menu-icon fa fa-pencil-square"></i>Presets
          <% end %></li>
        <li><%= link_to form_editor_vendors_dashboard_index_path do %>
              <i class="menu-icon fa fa-font"></i>Style form
          <% end %></li>
        <li><%= link_to contact_us_vendors_dashboard_index_path(id: current_vendor.id) do %>
            <i class="menu-icon fa fa-comment-o"></i>Contact Us
          <% end %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
</aside>
<!-- /#left-panel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swirble</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'swirblogo.png' %>

</head>

<body>
<!-- Preloader -->
<% if current_vendor.present? %>
    <%= render 'layouts/left_side_navbar' %>
<% end %>
<div id="right-panel" class="right-panel">
  <% if current_vendor.present? %>
      <%= render 'layouts/header' %>
  <% end %>
  <%= yield %>
  <% render 'layouts/footer' %>
</div>
</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <% application_name = ShopifyApp.configuration.application_name %>
  <title><%= application_name %></title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="app-wrapper">
  <div class="app-content">
    <main role="main">
      <%= yield %>
    </main>
  </div>
</div>

<%= render 'layouts/flash_messages' %>

<script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

<script type="text/javascript">
  ShopifyApp.init({
    apiKey: "<%= ShopifyApp.configuration.api_key %>",
    shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
    debug: <%= Rails.env.development? ? 'true' : 'false' %>,
    forceRedirect: true
  });
</script>

<% if content_for?(:javascript) %>
    <div id="ContentForJavascript" data-turbolinks-temporary>
      <%= yield :javascript %>
    </div>
<% end %>
</body>
</html>